-- INSTITUTIONS
INSERT INTO VS_13_EQUIPE_4.INSTITUTIONS (ID_INSTITUTION, COMPANY_NAME, CNPJ) -- ID 1
VALUES (VS_13_EQUIPE_4.SEQ_INSTITUTIONS.NEXTVAL, 'Institution 1', '01234567891011');

-- COMPETITORS
INSERT INTO VS_13_EQUIPE_4.COMPETITORS (ID_COMPETITOR, COMPANY_NAME, CNPJ) -- ID 1
VALUES (VS_13_EQUIPE_4.SEQ_COMPETITORS.NEXTVAL, 'InnovateTech Solutions', '01234567891011');

INSERT INTO VS_13_EQUIPE_4.COMPETITORS (ID_COMPETITOR, COMPANY_NAME, CNPJ) -- ID 2
VALUES (VS_13_EQUIPE_4.SEQ_COMPETITORS.NEXTVAL, 'Quantum Dynamics Innovations', '01234567891022');

INSERT INTO VS_13_EQUIPE_4.COMPETITORS (ID_COMPETITOR, COMPANY_NAME, CNPJ) -- ID 3
VALUES (VS_13_EQUIPE_4.SEQ_COMPETITORS.NEXTVAL, 'Nexus Innovations Group', '01234567891033');

INSERT INTO VS_13_EQUIPE_4.COMPETITORS (ID_COMPETITOR, COMPANY_NAME, CNPJ) -- ID 4
VALUES (VS_13_EQUIPE_4.SEQ_COMPETITORS.NEXTVAL, 'Stratosphere Solutions', '01234567891044');


-- PROCESSES
INSERT INTO VS_13_EQUIPE_4.PROCESSES (ID_PROCESS, PROCESS_NUMBER, TITLE, DESCRIPTION, STATUS, ID_INSTITUTION) -- ID 1
VALUES (VS_13_EQUIPE_4.SEQ_PROCESSES.NEXTVAL, '5d54b1', 'Licitação Pública para Contratação de Obra', 'Descrição da licitação', 1, 1);

INSERT INTO VS_13_EQUIPE_4.PROCESSES (ID_PROCESS, PROCESS_NUMBER, TITLE, DESCRIPTION, STATUS, ID_INSTITUTION) -- ID 2
VALUES (VS_13_EQUIPE_4.SEQ_PROCESSES.NEXTVAL, '74c0ge', 'Tomada de Preços', 'Descrição', 1, 1);


-- CONTACTS
INSERT INTO	VS_13_EQUIPE_4.CONTACTS (ID_CONTACT, "NAME", EMAIL, PHONE, PHONE_TYPE)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS.NEXTVAL, 'Contato publico', 'contato@institution1.com.br', '51911111111', 1); -- ID 1

INSERT INTO	VS_13_EQUIPE_4.CONTACTS (ID_CONTACT, "NAME", EMAIL, PHONE, PHONE_TYPE)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS.NEXTVAL, 'Contato comercial', 'contato@innovatetech.com.br', '51922222222', 2); -- ID 2

INSERT INTO	VS_13_EQUIPE_4.CONTACTS (ID_CONTACT, "NAME", EMAIL, PHONE, PHONE_TYPE)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS.NEXTVAL, 'Contato financeiro', null, '51933333333', 1); -- ID 3

INSERT INTO	VS_13_EQUIPE_4.CONTACTS (ID_CONTACT, "NAME", EMAIL, PHONE, PHONE_TYPE)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS.NEXTVAL, 'Contato markeging', 'contato@nexusinnovations.com.br', '51944444444', 2); -- ID 4

INSERT INTO	VS_13_EQUIPE_4.CONTACTS (ID_CONTACT, "NAME", EMAIL, PHONE, PHONE_TYPE)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS.NEXTVAL, 'Contato rh', null, '5195555555', 1); -- ID 5

-- ADRESSES
INSERT INTO	VS_13_EQUIPE_4.ADDRESSES (ID_ADDRESS, STREET, DISTRICT, "NUMBER", COMPLEMENT, CITY, STATE, ZIP_CODE)
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES.NEXTVAL, 'Street 1', 'District 1', 1, 'Complement 1', 'City 1', 'State 1', '12345671'); -- ID 1

INSERT INTO VS_13_EQUIPE_4.ADDRESSES (ID_ADDRESS, STREET, DISTRICT, "NUMBER", COMPLEMENT, CITY, STATE, ZIP_CODE) 
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES.NEXTVAL, 'Street 2', 'District 2', 2, 'Complement 2', 'City 2', 'State 2', '12345672'); -- ID 2

INSERT INTO VS_13_EQUIPE_4.ADDRESSES (ID_ADDRESS, STREET, DISTRICT, "NUMBER", COMPLEMENT, CITY, STATE, ZIP_CODE) 
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES.NEXTVAL, 'Street 3', 'District 3', 3, 'Complement 3', 'City 3', 'State 3', '12345673'); -- ID 3

INSERT INTO VS_13_EQUIPE_4.ADDRESSES (ID_ADDRESS, STREET, DISTRICT, "NUMBER", COMPLEMENT, CITY, STATE, ZIP_CODE) 
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES.NEXTVAL, 'Street 3', 'District 3', 4, 'Complement 3', 'City 3', 'State 3', '12345673'); -- ID 4

INSERT INTO VS_13_EQUIPE_4.ADDRESSES (ID_ADDRESS, STREET, DISTRICT, "NUMBER", COMPLEMENT, CITY, STATE, ZIP_CODE) 
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES.NEXTVAL, 'Street 3', 'District 3', 5, 'Complement 3', 'City 3', 'State 3', '12345673'); -- ID 5

-- DEPARTMENTS
INSERT INTO VS_13_EQUIPE_4.DEPARTMENTS (ID_DEPARTMENT, ID_INSTITUTION, ID_COMPETITOR, "NAME")
VALUES (1, 1, NULL, 'SECRETARIA DO AGRIDOCE');


-- USERS
INSERT INTO VS_13_EQUIPE_4.USERS (ID_USER, REGISTRATION, "NAME", "USER", "PASSWORD", "ROLE", "POSITION", ID_DEPARTMENT)
VALUES (VS_13_EQUIPE_4.SEQ_USERS.NEXTVAL, '564231', 'admin', 'admin', 'admin', 'all', 'admin', 1);


-- DOCUMENTS
INSERT INTO VS_13_EQUIPE_4.DOCUMENTS (ID_DOCUMENT, PROTOCOL, EXPIRATION_DATE, IS_SIGNED)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS.NEXTVAL, '1', TO_DATE('01-01-2025', 'dd-mm-yyyy'), 0);

INSERT INTO VS_13_EQUIPE_4.DOCUMENTS(ID_DOCUMENT, PROTOCOL, EXPIRATION_DATE, IS_SIGNED)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS.NEXTVAL, '2', TO_DATE('01-02-2025', 'dd-mm-yyyy'), 0);

INSERT INTO VS_13_EQUIPE_4.DOCUMENTS(ID_DOCUMENT, PROTOCOL, EXPIRATION_DATE, IS_SIGNED)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS.NEXTVAL, '3', TO_DATE('01-03-2025', 'dd-mm-yyyy'), 0);

INSERT INTO VS_13_EQUIPE_4.DOCUMENTS(ID_DOCUMENT, PROTOCOL, EXPIRATION_DATE, IS_SIGNED)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS.NEXTVAL, '4', TO_DATE('01-04-2025', 'dd-mm-yyyy'), 0);

-- CONTACTS ASSOCIATIONS
INSERT INTO VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (ID_CONTACT_ASSOCIATION, ID_CONTACT, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS.NEXTVAL, 1, null, 1);

INSERT INTO VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (ID_CONTACT_ASSOCIATION, ID_CONTACT, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS.NEXTVAL, 2, 1, null);

INSERT INTO VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (ID_CONTACT_ASSOCIATION, ID_CONTACT, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS.NEXTVAL, 3, 2, null);

INSERT INTO VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (ID_CONTACT_ASSOCIATION, ID_CONTACT, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS.NEXTVAL, 4, 3, null);

INSERT INTO VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (ID_CONTACT_ASSOCIATION, ID_CONTACT, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS.NEXTVAL, 5, 4, null);

-- ADRESSES ASSOCIATIONS
INSERT INTO VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (ID_ADDRESS_ASSOCIATION, ID_ADDRESS, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS.NEXTVAL, 1, NULL, 1);

INSERT INTO VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (ID_ADDRESS_ASSOCIATION, ID_ADDRESS, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS.NEXTVAL, 2, 1, NULL);

INSERT INTO VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (ID_ADDRESS_ASSOCIATION, ID_ADDRESS, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS.NEXTVAL, 3, 2, NULL);

INSERT INTO VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (ID_ADDRESS_ASSOCIATION, ID_ADDRESS, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS.NEXTVAL, 4, 3, NULL);

INSERT INTO VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (ID_ADDRESS_ASSOCIATION, ID_ADDRESS, ID_COMPETITOR, ID_INSTITUTION)
VALUES (VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS.NEXTVAL, 5, 4, NULL);

-- DOCUMENTS ASSOCIATIONS
INSERT INTO VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS (ID_DOCUMENT_ASSOCIATION, ID_DOCUMENT, ID_COMPETITOR, ID_PROCESS)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS_ASSOCIATIONS.NEXTVAL, 1, NULL, 1);

INSERT INTO VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS (ID_DOCUMENT_ASSOCIATION, ID_DOCUMENT, ID_COMPETITOR, ID_PROCESS)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS_ASSOCIATIONS.NEXTVAL, 2, NULL, 1);

INSERT INTO VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS (ID_DOCUMENT_ASSOCIATION, ID_DOCUMENT, ID_COMPETITOR, ID_PROCESS)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS_ASSOCIATIONS.NEXTVAL, 3, NULL, 2);

INSERT INTO VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS (ID_DOCUMENT_ASSOCIATION, ID_DOCUMENT, ID_COMPETITOR, ID_PROCESS)
VALUES (VS_13_EQUIPE_4.SEQ_DOCUMENTS_ASSOCIATIONS.NEXTVAL, 4, NULL, 2);

-- PROCESSES COMPETITORS
INSERT INTO VS_13_EQUIPE_4.PROCESSES_COMPETITORS (ID_PROCESS, ID_COMPETITOR, IS_ENABLED)
VALUES (1, 1, 0);

INSERT INTO VS_13_EQUIPE_4.PROCESSES_COMPETITORS (ID_PROCESS, ID_COMPETITOR, IS_ENABLED)
VALUES (1, 2, 0);

INSERT INTO VS_13_EQUIPE_4.PROCESSES_COMPETITORS (ID_PROCESS, ID_COMPETITOR, IS_ENABLED)
VALUES (2, 3, 0);

INSERT INTO VS_13_EQUIPE_4.PROCESSES_COMPETITORS (ID_PROCESS, ID_COMPETITOR, IS_ENABLED)
VALUES (2, 4, 0);

