CREATE USER AGIDOC IDENTIFIED BY oracle;

GRANT CONNECT TO AGIDOC;

GRANT CONNECT, RESOURCE, DBA TO AGIDOC;

GRANT CREATE SESSION TO AGIDOC;

GRANT DBA TO AGIDOC;

GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO AGIDOC;

GRANT UNLIMITED TABLESPACE TO AGIDOC;

GRANT CREATE MATERIALIZED VIEW TO AGIDOC;

GRANT CREATE TABLE TO AGIDOC;

GRANT GLOBAL QUERY REWRITE TO AGIDOC;

GRANT SELECT ANY TABLE TO AGIDOC;

CREATE TABLE AGIDOC."USER" (
	id NUMBER,
	email VARCHAR2(255) UNIQUE NOT NULL,
	password VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY (id)
);

CREATE SEQUENCE AGIDOC.SEQ_USER
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;