-- INSTITUTIONS
CREATE TABLE VS_13_EQUIPE_4.INSTITUTIONS (
  	ID_INSTITUTION NUMBER(38, 0),
  	CNPJ VARCHAR2(14) UNIQUE NOT NULL,
  	COMPANY_NAME VARCHAR2(100) NOT NULL,
  	CONSTRAINT PK_INSTITUTIONS PRIMARY KEY (ID_INSTITUTION)
);

CREATE SEQUENCE SEQ_INSTITUTIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- PROCESSES
CREATE TABLE VS_13_EQUIPE_4.PROCESSES (
  	ID_PROCESS NUMBER(38, 0),
  	TITLE VARCHAR2(255) NOT NULL,
  	DESCRIPTION VARCHAR2(255) NOT NULL,
  	STATUS NUMBER(1) NOT NULL CHECK (STATUS IN (0, 1)),
  	ID_INSTITUTION NUMBER(38, 0) NOT NULL,
  	ID_CONTRACTED NUMBER(38, 0),
  	CONSTRAINT PK_PROCESSES PRIMARY KEY (ID_PROCESS)
);

CREATE SEQUENCE SEQ_PROCESSES
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- USERS
CREATE TABLE VS_13_EQUIPE_4.USERS (
  	ID_USER NUMBER(38, 0),
  	REGISTRATION VARCHAR2(255) NOT NULL,
  	NAME VARCHAR2(255) NOT NULL,
  	USER VARCHAR2(255) NOT NULL,
  	ROLE VARCHAR2(255) NOT NULL,
  	POSITION VARCHAR2(255) NOT NULL,
  	ID_DEPARTAMENTS VARCHAR2(255) NOT NULL,
  	CONSTRAINT PK_USERS PRIMARY KEY (ID_USER)
);

CREATE SEQUENCE SEQ_USERS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- COMPETITORS
CREATE TABLE VS_13_EQUIPE_4.COMPETITORS (
  	ID_COMPETITOR NUMBER(38, 0),
  	COMPANY_NAME VARCHAR2(100) NOT NULL,
  	CNPJ VARCHAR2(14) UNIQUE NOT NULL,
  	IS_ENABLED NUMBER(1) NOT NULL CHECK (STATUS IN (0, 1)),
  	CONSTRAINT PK_COMPETITORS PRIMARY KEY (ID_COMPETITOR)
);

CREATE SEQUENCE SEQ_COMPETITORS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- DOCUMENTS
CREATE TABLE VS_13_EQUIPE_4.DOCUMENTS (
  	ID_DOCUMENT NUMBER(38, 0) NOT NULL,
  	PROTOCOL VARCHAR2(50) UNIQUE NOT NULL,
  	EXPIRATION_DATE DATE NOT NULL,
  	IS_SIGNED NUMBER(1) NOT NULL CHECK (SIGNED IN (0, 1)),
  	FILE BLOB NOT NULL,
  	ID_SIGNATURE NUMBER(38, 0),
  	CONSTRAINT PK_DOCUMENTS PRIMARY KEY (ID_DOCUMENT)
);

CREATE SEQUENCE SEQ_DOCUMENTS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- CONTACTS
CREATE TABLE VS_13_EQUIPE_4.CONTACTS (
  	ID_CONTACT NUMBER(38, 0) NOT NULL,
  	NAME VARCHAR2(255) NOT NULL,
  	EMAIL VARCHAR2(100) UNIQUE,
  	PHONE VARCHAR2(50) NOT NULL,
  	TYPE NUMBER(1) NOT NULL CHECK (TYPE IN (0, 1)),
  	CONSTRAINT PK_CONTACTS PRIMARY KEY (ID_CONTACT)
);

CREATE SEQUENCE SEQ_CONTACTS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- ADRESSES
CREATE TABLE VS_13_EQUIPE_4.ADDRESSES (
  	ID_ADDRESS NUMBER(38, 0) NOT NULL,
  	STREET VARCHAR2(255) NOT NULL,
  	DISTRICT VARCHAR2(255) NOT NULL,
  	NUMBER VARCHAR2(255) NOT NULL,
  	COMPLEMENT VARCHAR2(255) NOT NULL,
  	ZIPCODE VARCHAR2(8) NOT NULL,
  	CITY VARCHAR2(100) NOT NULL,
  	STATE VARCHAR2(100) NOT NULL,
  	CONSTRAINT PK_ADRESSES PRIMARY KEY (ID_ADDRESS)
);

CREATE SEQUENCE SEQ_ADDRESSES
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- DEPARTAMENTS
CREATE TABLE VS_13_EQUIPE_4.DEPARTAMENTS (
	ID_DEPARTAMENT NUMBER(38, 0) NOT NULL,
	ID_INSTITUTION NUMBER(38, 0),
	ID_COMPETITOR NUMBER(38, 0),
  	NAME VARCHAR2(255) NOT NULL,
  	CONSTRAINT PK_DEPARTAMENTS PRIMARY KEY (ID_DEPARTAMENTS),
  	CONSTRAINT FK_DEPARTAMENTS_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES INSTITUTIONS(ID_INSTITUTION),
  	CONSTRAINT FK_DEPARTAMENTS_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES COMPETITORS(ID_COMPETITOR)
);

CREATE SEQUENCE SEQ_DEPARTAMENTS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- CONTACTS ASSOCIATIONS
CREATE TABLE VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (
  	ID_CONTACT_ASSOCIATION NUMBER(38, 0) NOT NULL,
  	ID_CONTACT NUMBER(38, 0) NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0),
  	ID_INSTITUTION NUMBER(38, 0),
  	CONSTRAINT PK_CONTACTS_ASSOCIATIONS PRIMARY KEY (ID_ASSOCIATION),
  	CONSTRAINT FK_CONTACT_ASSOCIATIONS_CONTACTS FOREIGN KEY (ID_CONTACT) REFERENCES CONTACTS(ID_CONTACT),
  	CONSTRAINT FK_CONTACT_ASSOCIATIONS_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES COMPETITORS(ID_COMPETITOR),
  	CONSTRAINT FK_CONTACT_ASSOCIATIONS_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES INTITUTIONS(ID_INSTITUTION)
);

CREATE SEQUENCE SEQ_CONTACTS_ASSOCIATIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- ADRESSES ASSOCIATIONS
CREATE TABLE VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (
  	ID_ADRESS_ASSOCIATION NUMBER(38, 0) NOT NULL,
  	ID_ADDRESS NUMBER(38, 0) NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0),
  	ID_INSTITUTION NUMBER(38, 0),
  	CONSTRAINT PK_ADRESSES_ASSOCIATIONS PRIMARY KEY (ID_ASSOCIATION),
  	CONSTRAINT FK_ADRESSES_ASSOCIATIONS_ADRESSES FOREIGN KEY (ID_ADDRESS) REFERENCES ADRESSES(ID_ADDRESS),
  	CONSTRAINT FK_ADRESSES_ASSOCIATIONS_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES COMPETITORS(ID_COMPETITOR),
  	CONSTRAINT FK_ADRESSES_ASSOCIATIONS_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES INSTITUTIONS(ID_INSTITUTION)
);

CREATE SEQUENCE SEQ_ADDRESSES_ASSOCIATIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- DOCUMENTS ASSOCIATIONS
CREATE TABLE VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS (
  	ID_DOCUMENT_ASSOCIATION NUMBER(38, 0) NOT NULL,
  	ID_DOCUMENT NUMBER(38, 0) NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0),
  	ID_PROCESS NUMBER(38, 0),
  	CONSTRAINT PK_DOCUMENTS_ASSOCIATIONS PRIMARY KEY (ID_ASSOCIATION),
 	CONSTRAINT FK_DOCUMENTS_ASSOCIATIONS_DOCUMENTS FOREIGN KEY (ID_DOCUMENT) REFERENCES DOCUMENTS(ID_DOCUMENT),
  	CONSTRAINT FK_DOCUMENTS_ASSOCIATIONS_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES COMPETITORS(ID_COMPETITOR),
  	CONSTRAINT FK_DOCUMENTS_ASSOCIATIONS_PROCESSES FOREIGN KEY (ID_PROCESS) REFERENCES PROCESSES(ID_PROCESS)
);

CREATE SEQUENCE SEQ_DOCUMENTS_ASSOCIATIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- PROCESSES COMPETITORS
CREATE TABLE VS_13_EQUIPE_4.PROCESSES_COMPETITORS (
  ID_PROCESS NUMBER(38, 0) NOT NULL,
  ID_COMPETITOR NUMBER(38, 0) NOT NULL
  CONSTRAINT PK_PROCESSES_COMPETITORS PRIMARY KEY (ID_PROCESS, ID_COMPETITOR),
  CONSTRAINT FK_PROCESSES_COMPETITORS_PROCESSES FOREIGN KEY (ID_PROCESS) REFERENCES PROCESSES(ID_PROCESS),
  CONSTRAINT FK_PROCESSES_COMPETITORS_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES COMPETITORS(ID_COMPETITOR)
);