-- DROP TABLES
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.PROCESSES_COMPETITORS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.DOCUMENTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.USERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.DEPARTMENTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.ADDRESSES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.CONTACTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.PROCESSES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.COMPETITORS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VS_13_EQUIPE_4.INSTITUTIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


-- DROP SEQUENCES
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_ADDRESSES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_COMPETITORS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_CONTACTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_DEPARTMENTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_DOCUMENTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_DOCUMENTS_ASSOCIATIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_INSTITUTIONS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_PROCESSES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE VS_13_EQUIPE_4.SEQ_USERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;


-- INSTITUTIONS
CREATE TABLE VS_13_EQUIPE_4.INSTITUTIONS (
  	ID_INSTITUTION NUMBER(38, 0) NOT NULL,
  	COMPANY_NAME VARCHAR2(100) NOT NULL,
  	CNPJ VARCHAR2(14) UNIQUE NOT NULL,
  	CONSTRAINT PK_INSTITUTIONS PRIMARY KEY (ID_INSTITUTION)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_INSTITUTIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- COMPETITORS
CREATE TABLE VS_13_EQUIPE_4.COMPETITORS (
  	ID_COMPETITOR NUMBER(38, 0) NOT NULL,
  	COMPANY_NAME VARCHAR2(100) NOT NULL,
  	CNPJ VARCHAR2(14) UNIQUE NOT NULL,
  	CONSTRAINT PK_COMPETITORS PRIMARY KEY (ID_COMPETITOR)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_COMPETITORS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- PROCESSES
CREATE TABLE VS_13_EQUIPE_4.PROCESSES (
  	ID_PROCESS NUMBER(38, 0) NOT NULL,
  	PROCESS_NUMBER VARCHAR2(255) NOT NULL,
  	TITLE VARCHAR2(100) NOT NULL,
  	DESCRIPTION VARCHAR2(255) NOT NULL,
  	STATUS NUMBER(1) NOT NULL CHECK (STATUS IN (0, 1, 2, 3)),
  	ID_INSTITUTION NUMBER(38, 0) NOT NULL,
  	ID_CONTRACTED NUMBER(38, 0),
  	CONSTRAINT PK_PROCESSES PRIMARY KEY (ID_PROCESS),
  	CONSTRAINT FK_PROCESSES_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES VS_13_EQUIPE_4.INSTITUTIONS(ID_INSTITUTION),
  	CONSTRAINT FK_PROCESSES_CONTRACTED FOREIGN KEY (ID_CONTRACTED) REFERENCES VS_13_EQUIPE_4.COMPETITORS(ID_COMPETITOR)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_PROCESSES
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- CONTACTS
CREATE TABLE VS_13_EQUIPE_4.CONTACTS (
  	ID_CONTACT NUMBER(38, 0) NOT NULL,
  	NAME VARCHAR2(100) NOT NULL,
  	EMAIL VARCHAR2(100) UNIQUE,
  	PHONE VARCHAR2(50) NOT NULL,
  	PHONE_TYPE NUMBER(1) NOT NULL CHECK (PHONE_TYPE IN (1, 2)),
  	CONSTRAINT PK_CONTACTS PRIMARY KEY (ID_CONTACT)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_CONTACTS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- ADRESSES
CREATE TABLE VS_13_EQUIPE_4.ADDRESSES (
  	ID_ADDRESS NUMBER(38, 0) NOT NULL,
  	STREET VARCHAR2(255) NOT NULL,
  	DISTRICT VARCHAR2(255) NOT NULL,
  	"NUMBER" NUMBER(10, 0) NOT NULL,
  	COMPLEMENT VARCHAR2(255) NOT NULL,
  	CITY VARCHAR2(100) NOT NULL,
  	STATE VARCHAR2(100) NOT NULL,
  	ZIP_CODE VARCHAR2(8) NOT NULL,
  	CONSTRAINT PK_ADRESSES PRIMARY KEY (ID_ADDRESS)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_ADDRESSES
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- DEPARTMENTS
CREATE TABLE VS_13_EQUIPE_4.DEPARTMENTS (
	ID_DEPARTMENT NUMBER(38, 0) NOT NULL,
	ID_INSTITUTION NUMBER(38, 0),
	ID_COMPETITOR NUMBER(38, 0),
  	NAME VARCHAR2(255) NOT NULL,
  	CONSTRAINT CHK_DEPARTMENTS_ATRIBUTION CHECK ((CASE WHEN ID_INSTITUTION IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN ID_COMPETITOR IS NOT NULL THEN 1 ELSE 0 END) = 1),
  	CONSTRAINT PK_DEPARTMENTS PRIMARY KEY (ID_DEPARTMENT),
  	CONSTRAINT FK_DEPARTMENTS_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES VS_13_EQUIPE_4.INSTITUTIONS(ID_INSTITUTION),
  	CONSTRAINT FK_DEPARTMENTS_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES VS_13_EQUIPE_4.COMPETITORS(ID_COMPETITOR)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_DEPARTMENTS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- USERS
CREATE TABLE VS_13_EQUIPE_4.USERS (
  	ID_USER NUMBER(38, 0) NOT NULL,
  	REGISTRATION VARCHAR2(100) UNIQUE NOT NULL,
  	NAME VARCHAR2(100) NOT NULL,
  	"USER" VARCHAR2(100) NOT NULL,
  	PASSWORD VARCHAR2(100) NOT NULL,
  	"ROLE" VARCHAR2(100) NOT NULL,
  	"POSITION" VARCHAR2(100) NOT NULL,
  	ID_DEPARTMENT NUMBER(38, 8) NOT NULL,
  	CONSTRAINT PK_USERS PRIMARY KEY (ID_USER),
  	CONSTRAINT FK_USERS_DEPARTMENTS FOREIGN KEY (ID_DEPARTMENT) REFERENCES VS_13_EQUIPE_4.DEPARTMENTS(ID_DEPARTMENT)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_USERS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- DOCUMENTS
CREATE TABLE VS_13_EQUIPE_4.DOCUMENTS (
  	ID_DOCUMENT NUMBER(38, 0) NOT NULL,
  	PROTOCOL VARCHAR2(50) UNIQUE NOT NULL,
  	EXPIRATION_DATE DATE NOT NULL,
  	IS_SIGNED NUMBER(1) NOT NULL CHECK (IS_SIGNED IN (0, 1)),
  	"FILE" BLOB, -- NOT NULL 
  	ID_SIGNATURE NUMBER(38, 0), -- IRÁ VIRAR UMA REFERÊNCIA DE UMA TABELA DE JUNÇÃO
  	CONSTRAINT PK_DOCUMENTS PRIMARY KEY (ID_DOCUMENT),
  	CONSTRAINT FK_DOCUMENTS_SIGNATURE FOREIGN KEY (ID_SIGNATURE) REFERENCES VS_13_EQUIPE_4.USERS(ID_USER)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_DOCUMENTS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- CONTACTS ASSOCIATIONS
CREATE TABLE VS_13_EQUIPE_4.CONTACTS_ASSOCIATIONS (
  	ID_CONTACT_ASSOCIATION NUMBER(38, 0) NOT NULL,
  	ID_CONTACT NUMBER(38, 0) UNIQUE NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0),
  	ID_INSTITUTION NUMBER(38, 0),
  	CONSTRAINT CHK_CONT_ASSO_ATRIBUTION CHECK ((CASE WHEN ID_INSTITUTION IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN ID_COMPETITOR IS NOT NULL THEN 1 ELSE 0 END) = 1),
  	CONSTRAINT PK_CONTACTS_ASSOCIATIONS PRIMARY KEY (ID_CONTACT_ASSOCIATION),
  	CONSTRAINT FK_CONT_ASSO_CONTACTS FOREIGN KEY (ID_CONTACT) REFERENCES VS_13_EQUIPE_4.CONTACTS(ID_CONTACT),
  	CONSTRAINT FK_CONT_ASSO_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES VS_13_EQUIPE_4.COMPETITORS(ID_COMPETITOR),
  	CONSTRAINT FK_CONT_ASSO_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES VS_13_EQUIPE_4.INSTITUTIONS(ID_INSTITUTION)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_CONTACTS_ASSOCIATIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- ADRESSES ASSOCIATIONS
CREATE TABLE VS_13_EQUIPE_4.ADDRESSES_ASSOCIATIONS (
  	ID_ADDRESS_ASSOCIATION NUMBER(38, 0) NOT NULL,
  	ID_ADDRESS NUMBER(38, 0) UNIQUE NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0),
  	ID_INSTITUTION NUMBER(38, 0),
  	CONSTRAINT CHK_ADDR_ASSO_ATRIBUTION CHECK ((CASE WHEN ID_INSTITUTION IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN ID_COMPETITOR IS NOT NULL THEN 1 ELSE 0 END) = 1),
  	CONSTRAINT PK_ADDRESSES_ASSOCIATIONS PRIMARY KEY (ID_ADDRESS_ASSOCIATION),
  	CONSTRAINT FK_ADDR_ASSO_ADDRESSES FOREIGN KEY (ID_ADDRESS) REFERENCES VS_13_EQUIPE_4.ADDRESSES(ID_ADDRESS),
  	CONSTRAINT FK_ADDR_ASSO_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES VS_13_EQUIPE_4.COMPETITORS(ID_COMPETITOR),
  	CONSTRAINT FK_ADDR_ASSO_INSTITUTIONS FOREIGN KEY (ID_INSTITUTION) REFERENCES VS_13_EQUIPE_4.INSTITUTIONS(ID_INSTITUTION)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_ADDRESSES_ASSOCIATIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- DOCUMENTS ASSOCIATIONS
CREATE TABLE VS_13_EQUIPE_4.DOCUMENTS_ASSOCIATIONS (
  	ID_DOCUMENT_ASSOCIATION NUMBER(38, 0) NOT NULL,
  	ID_DOCUMENT NUMBER(38, 0) NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0),
  	ID_PROCESS NUMBER(38, 0),
  	CONSTRAINT CHK_DOC_ASSO_ATRIBUTION CHECK ((CASE WHEN ID_PROCESS IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN ID_COMPETITOR IS NOT NULL THEN 1 ELSE 0 END) = 1),
  	CONSTRAINT PK_DOCUMENTS_ASSOCIATIONS PRIMARY KEY (ID_DOCUMENT_ASSOCIATION),
 	CONSTRAINT FK_DOC_ASSO_DOCUMENTS FOREIGN KEY (ID_DOCUMENT) REFERENCES VS_13_EQUIPE_4.DOCUMENTS(ID_DOCUMENT),
  	CONSTRAINT FK_DOC_ASSO_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES VS_13_EQUIPE_4.COMPETITORS(ID_COMPETITOR),
  	CONSTRAINT FK_DOC_ASSO_PROCESSES FOREIGN KEY (ID_PROCESS) REFERENCES VS_13_EQUIPE_4.PROCESSES(ID_PROCESS)
);

CREATE SEQUENCE VS_13_EQUIPE_4.SEQ_DOCUMENTS_ASSOCIATIONS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;


-- PROCESSES COMPETITORS
CREATE TABLE VS_13_EQUIPE_4.PROCESSES_COMPETITORS (
  	ID_PROCESS NUMBER(38, 0) NOT NULL,
  	ID_COMPETITOR NUMBER(38, 0) NOT NULL,
  	IS_ENABLED NUMBER(1) NOT NULL CHECK (IS_ENABLED IN (0, 1)),
 	CONSTRAINT PK_PROCESSES_COMPETITORS PRIMARY KEY (ID_PROCESS, ID_COMPETITOR),
  	CONSTRAINT FK_PROC_COMPE_PROCESSES FOREIGN KEY (ID_PROCESS) REFERENCES VS_13_EQUIPE_4.PROCESSES(ID_PROCESS),
  	CONSTRAINT FK_PROC_COMPE_COMPETITORS FOREIGN KEY (ID_COMPETITOR) REFERENCES VS_13_EQUIPE_4.COMPETITORS(ID_COMPETITOR)
);